name: 'Setup Atlas'
description: 'Installs a specific version of Atlas'
branding:
  icon: database
  color: 'blue'
author: 'Ariga'
inputs:
  version:
    description: 'Which version of Atlas to install, in the format of "v0.14.1"'
    required: false
    default: 'latest'
  flavor:
    description: 'Which flavor of Atlas to install'
    required: false
  cloud-token:
    description: API token to authenticate to an Atlas Cloud organization
    required: false
runs:
  using: "composite"
  steps:
    - if: runner.os != 'Windows'
      shell: bash
      run: |
        if [ -n "${{ inputs.flavor }}" ]; then
          curl -sSf https://atlasgo.sh | ATLAS_FLAVOR=${{ inputs.flavor }} CI=true sh
        else
          curl -sSf https://atlasgo.sh | ATLAS_VERSION=${{ inputs.version }} CI=true sh
        fi
    - if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $version = "${{ inputs.version }}"
        if ("${{ inputs.flavor }}" -ne "") {
          $version = "extended"
        }
        $url = "https://release.ariga.io/atlas/atlas-windows-amd64-$version.exe"
        $targetPath = "$env:LocalAppData\Programs\Atlas"
        New-Item -Path $targetPath -ItemType Directory -Force
        curl -L $url -o "$targetPath\atlas.exe"
        Add-Content $env:GITHUB_PATH "$targetPath"
    - name: Login to Atlas
      if: inputs.cloud-token != null
      shell: bash
      run: atlas login --token ${{ inputs.cloud-token }}
